import zipfile

# Contenu du fichier index.html
html_content = """<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Permis de Conduire – Récupération & Assistance</title>
  <meta name="description" content="Assistance pour récupérer un permis de conduire saisi ou suspendu. Service pour la Belgique et les Pays-Bas. Contact via Telegram uniquement.">
  <meta name="keywords" content="récupérer permis saisi, permis suspendu Belgique, permis Pays-Bas, aide permis de conduire, contact Telegram">
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      background: #f5f5f5;
      color: #333;
    }
    header {
      background: #003399;
      color: white;
      padding: 40px 20px;
      text-align: center;
    }
    .container {
      padding: 20px;
      max-width: 1000px;
      margin: auto;
    }
    .card {
      background: white;
      margin-bottom: 20px;
      border-radius: 10px;
      overflow: hidden;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    }
    .card img {
      width: 100%;
    }
    .card-content {
      padding: 20px;
    }
    footer {
      background: #222;
      color: white;
      text-align: center;
      padding: 20px;
      margin-top: 40px;
    }
    .contact {
      text-align: center;
      margin: 40px 0;
    }
    .contact a {
      display: inline-block;
      margin: 10px;
      padding: 15px 25px;
      border-radius: 8px;
      color: white;
      text-decoration: none;
      font-weight: bold;
      background: #0088cc;
    }
  </style>
</head>
<body>

<header>
  <h1>Assistance Permis – Belgique & Pays-Bas</h1>
  <p>Récupération de permis saisis ou suspendus | Contact via Telegram</p>
</header>

<div class="container">

  <div class="card">
    <img src="https://via.placeholder.com/1000x400?text=Permis+Saisi" alt="Permis saisi">
    <div class="card-content">
      <h2>Permis saisi ? Nous pouvons vous aider.</h2>
      <p>Vous avez perdu votre permis suite à une saisie ou une suspension administrative ? Contactez-nous pour une assistance discrète et rapide, en toute confidentialité.</p>
    </div>
  </div>

  <div class="card">
    <img src="https://via.placeholder.com/1000x400?text=Types+de+Permis" alt="Types de permis">
    <div class="card-content">
      <h2>Types de permis concernés</h2>
      <p>Nous aidons à régulariser les permis B, A, AM, C (voitures, motos, scooters, poids lourds) pour la Belgique et les Pays-Bas.</p>
    </div>
  </div>

  <div class="contact">
    <h2>Contact Telegram</h2>
    <p>Disponible uniquement via Telegram :</p>
    <a href="https://t.me/Ckhloee" target="_blank">@Ckhloee</a>
  </div>

</div>

<footer>
  <p>&copy; 2025 Assistance Permis – Tous droits réservés</p>
</footer>

</body>
</html>
"""

# Création de l'archive ZIP avec le fichier index.html
with zipfile.ZipFile("site_permis.zip", "w") as zf:
    zf.writestr("index.html", html_content)

print("Le fichier 'site_permis.zip' a été généré avec succès.")
